In [ ]:
import pandas as pd
from pathlib import Path

In [14]:
DATA_DIR = Path("..") / "dataset"
df_train = pd.read_json(DATA_DIR / "train.json")
df_test = pd.read_json(DATA_DIR / "test.json")

df_train.head()

,transaction_date,year,month,dept_code,dept_name,region_code,region_name,transaction_type,future_sale,property_value,...,area_apt_1_room,area_apt_2_rooms,area_apt_3_rooms,area_apt_4_rooms,area_apt_5plus_rooms,area_house_1_room,area_house_2_rooms,area_house_3_rooms,area_house_4_rooms,area_house_5plus_rooms
0,2015-06-29,2015,6,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,58000.0,...,0,0,0,0,0,0,0,0,0,0
1,2020-11-26,2020,11,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,58000.0,...,34,0,0,0,0,0,0,0,0,0
2,2016-03-16,2016,3,86,Vienne,75,Nouvelle-Aquitaine,Vente en l'état futur d'achèvement,True,169000.0,...,0,0,61,0,0,0,0,0,0,0
3,2020-06-19,2020,6,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,73000.0,...,0,0,60,0,0,0,0,0,0,0
4,2021-05-26,2021,5,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,208000.0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df_train.shape

(27368, 48)

In [15]:
df_test.head()

,transaction_date,year,month,dept_code,dept_name,region_code,region_name,transaction_type,future_sale,num_lots,...,area_apt_1_room,area_apt_2_rooms,area_apt_3_rooms,area_apt_4_rooms,area_apt_5plus_rooms,area_house_1_room,area_house_2_rooms,area_house_3_rooms,area_house_4_rooms,area_house_5plus_rooms
0,2015-03-11,2015,3,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,2,...,26,0,0,0,0,0,0,0,0,0
1,2019-03-16,2019,3,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,0,...,0,0,0,0,0,0,0,0,84,0
2,2020-06-18,2020,6,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,0,...,0,0,0,0,0,0,0,0,0,160
3,2016-09-02,2016,9,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,0,...,0,0,0,0,0,0,0,0,0,147
4,2015-01-12,2015,1,86,Vienne,75,Nouvelle-Aquitaine,Vente,False,0,...,0,0,0,0,0,0,0,0,0,0